### ISSUE TITLE
Error while checking if a plugin is active

### ISSUE THREAD

**Issue by ibndawood** [facebook/facebook-for-woocommerce#2448]
Found the error message below in the error log while sweeping the logs.
```
PHP Fatal error: Uncaught Error: Class 'WooCommerce\Facebook\Framework\Helper' not found in /srv/htdocs/wp-content/plugins/facebook-for-woocommerce/includes/Framework/Plugin.php:838 
Stack trace: 
#0 /srv/htdocs/wp-content/plugins/facebook-for-woocommerce/includes/Integrations/Bookings.php(41): WooCommerce\Facebook\Framework\Plugin->is_plugin_active('woocommerce-boo...') 
#1 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): WooCommerce\Facebook\Integrations\Bookings->add_hooks('') 
#2 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) 
#3 /wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array) 
#4 /wordpress/core/6.1.1/wp-settings.php(617): do_action('init') 
#5 /srv/htdocs/wp-config.php(83): require_once('/wordpress/core...') 
#6 /wordpress/core/6.1.1/wp-load.php(55): require_once('/srv/htdocs/wp-...') 
#7 /wordpress/core/6.1.1/wp-admin/admin-ajax.php(22): require_once('/wordpress/core...') 
#8 {main} thrown in /srv/htdocs/wp-content/plugins/facebook-for-woocommerce/includes/Framework/Plugin.php on line 838
```

**Comment by rawdreeg** [comment]
Have you been able to reproduce this, @ibndawood? If so, can you share your system details?

**Comment by rawdreeg** [comment]
Yes. a bit of a strange one. I haven't been able to reproduce it. It looks like: WooCommerce\Facebook\Framework\Helper wasn't found from the plugin, but I checked they share the same namespace. So it shouldn't be a problem.
